Algoritmo "Aula03_Exercicio20"
// Exercício 20 – Pesqisa de SAtisfação: Uma empresa entrevistou vários clientes.
//Para cada cliente leia uma nota de 1 a 5. A pesquisa termina
//quando o usuário informar 0.
//Ao final informe: Quantidade de respostas, Média das notas,
//Quantos responderam 5, Quantos responderam 1.
// Autor(a)    : Victor Menezes Da Silva Reis
// Data atual  : 07/08/2026
Var
   // Seção de Declarações das variáveis
   qtd = inteiro
   media = real
   nota = real
   soma = real



Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Informe a nota:(1 a 5)")
   leia(nota)
   cliente <- cliente + 1

   enquanto nota > 0 faca
      escreval("Informe a nota:(1 a 5)")
      leia(nota)
      cliente <- cliente + 1
      soma <- soma + nota
      
   fimenquanto


Fimalgoritmo