Algoritmo "Aula04_Exercício05"
// Exercício 5 – Processo Seletivo: Leia a nota de um candidato.
//Considere que a nota mínima é 70 pontos.
//Informe se ele foi aprovado ou reprovado.
// Autor(a)    : Victor Menezes Da Silva Reis
// Data atual  : 08/08/2026
Var
   // Seção de Declarações das variáveis
   nota : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Informe a sua nota:")
   leia(nota)

   se (nota >= 70) entao
      escreval("Você foi Aprovado!")
   senao
        escreval("Você foi Reprovado!")
   fimse


Fimalgoritmo