Algoritmo "Aula03_Exercicio01"
// Descrição: Exercício 1 – Dobro e Triplo de um Número : Crie um algoritmo que leia um número inteiro e exiba o seu dobro e o seu triplo
// Autor(a): Victor Menezes Da Silva Reis
// Data: 04/08/2026

Var
// Seção de Declarações das variáveis
	numero : inteiro

Inicio
	// Ler um número
	escreval("Informe um número: ")
  leia(numero)
  
  // Mostrar no console o dobro e o triplo do número digitado
  escreval(numero)
  escreval("O dobro é:", numero * 2)
  escreval("O triplo é:", numero * 3)


fimalgoritmo