Algoritmo "Aula03_Exercicio12"
// Exercício 12 – Contagem regressiva: Crie um algoritmo que exiba os números de 10 até 1 e no final escreva “Feliz Ano novo!”
// Autor(a)    : Victor Menezes Da Silva Reis
// Data atual  : 05/08/2026
Var
   // Seção de Declarações das variáveis
   // Contador
   i : inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   // Inicializar o contador com 10
   i <- 10
   // Estrutura de repetição
   enquanto i >= 1 faca
      escreval(i)
      i <- i - 1 // decrementar o contador
   fimenquanto
   escreval("Feliz Ano novo!")
Fimalgoritmo