Algoritmo "Aula06_Exercício04"
// Exercício 4 – Dois em dois: Leia um número N digitado pelo usuário e
//imprima de 1 até N, de dois em dois
// Autor(a)    : Victor Menezes
// Data atual  : 10/08/2026
Var
   // Seção de Declarações das variáveis
   i : inteiro
   n : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Informe até quanto você deseja pular em 2:")
   leia(n)
   para i de 1 até n passo 2 faca
        escreval(i)
   fimpara

Fimalgoritmo